name: release
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  getassets:
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1
        with:
          tag: 'alarm-aarch64'
          fileName: '*'
          out-file-path: 'oldassets'
      - run: ls -la ${{ github.workspace }}/oldassets
      - name: zip artifacts
        if: always()
        run: |
          zip -j0 oldassets.zip oldassets/*
      - uses: actions/upload-artifact@v4
        with:
          name: old-assets
          path: oldassets.zip

  build:
    needs: getassets
    runs-on: ubuntu-24.04-arm
    continue-on-error: true
    strategy:
      matrix:
        package: [gitweb-dlagent,
                  linux-aarch64-rk3588-collabora-git linux-aarch64-rk3588-collabora-git-headers,
                  linux-aarch64-rockchip-bsp5.10-radxa-git linux-aarch64-rockchip-bsp5.10-radxa-git-headers,
                  linux-aarch64-rockchip-bsp6.1-armbian-git linux-aarch64-rockchip-bsp6.1-armbian-git-headers,
                  linux-aarch64-rockchip-bsp6.1-joshua-git linux-aarch64-rockchip-bsp6.1-joshua-git-headers,
                  linux-aarch64-rockchip-bsp6.1-boogie-git linux-aarch64-rockchip-bsp6.1-boogie-headers-git linux-aarch64-rockchip-bsp6.1-boogie-dtb-git linux-aarch64-rockchip-bsp6.1-boogie-openvfd-git,
                  librga-multi,
                  acestream-media-bin,
                  8852be-dkms-git,
                  8852bu-dkms-git,
                  iwlwifi-backport-dkms-git,
                  r8125-dkms-git,
                  dri2to3-git,
                  bcm4335-firmware,
                  gl4es-git,
                  kodi-mpp-git,
                  kodi-binary-addons-git,
                  libmali-valhall-g610-base libmali-valhall-g610-dummy libmali-valhall-g610-gbm libmali-valhall-g610-x11-gbm libmali-valhall-g610-wayland-gbm libmali-valhall-g610-x11-wayland-gbm,
                  mesa-panvk-git,
                  mesa-panfork-git,
                  mpp-git,
                  ffmpeg-mpp-git,
                  firefox-mpp,
                  libv4l-rkmpp-git,
                  v4l-utils-mpp,
                  sunshine-mpp-git,
                  dolphin-emu dolphin-emu-tool,
                  agr-git,
                  mpv-mpp]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: old-assets
      - name: prepare old packages
        run: |
          mkdir -p agr/tarballs/native/repo
          mkdir -p upload
          unzip -d agr/tarballs/native/repo oldassets.zip
          packages='${{ matrix.package }}'
          for package in ${packages}; do
            cp -rf agr/tarballs/native/repo/$package-*.pkg.* upload/ || true
          done
          ls -la agr/tarballs/native/repo
          ls -la upload
      - name: Build ${{ matrix.package }}
        uses: hbiyik/agr@master
        with:
          package: ${{ matrix.package }}
          skippgpcheck: true
          ignorearch: true
      - name: prepare built packages to upload
        if: always()
        run: |
          packages='${{ matrix.package }}'
          for package in ${packages}; do
            cp -rf agr/tarballs/native/repo/$package-*.pkg.* upload/ || true
          done
          zip -j0 "${{ matrix.package }}.zip" upload/*
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-${{ matrix.package }}
          path: ${{ matrix.package }}.zip

  genrepo:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: zips
          merge-multiple: true
      - run: |
          mkdir -p repo
          ls -la zips
          unzip -o -d repo "zips/*"
          ls -la repo
      - uses: actions/checkout@v4
        with:
          path: agrrepo
      - uses: ./agrrepo/.github/actions/sync
        with:
          tag: alarm-aarch64
          reponame: boogie
